"""FileSystem Service稳定错误码。"""

FILE_NOT_FOUND = "SHF-SVC-FILE-NOT_FOUND"
PERMISSION_DENIED = "SHF-SVC-FILE-PERMISSION_DENIED"
INVALID_PATH = "SHF-SVC-FILE-INVALID_PATH"
FILE_TOO_LARGE = "SHF-SVC-FILE-TOO_LARGE"
UNSUPPORTED_TYPE = "SHF-SVC-FILE-UNSUPPORTED_TYPE"
DELETE_CONFIRM_REQUIRED = "SHF-SVC-FILE-DELETE_CONFIRM_REQUIRED"
MCP_UNAVAILABLE = "SHF-SVC-FILE-MCP_UNAVAILABLE"
