"""Content Service稳定错误码。"""

CONTENT_REQUEST_INVALID = "SHF-CONTENT-REQUEST-INVALID"
CONTENT_PLAN_FAILED = "SHF-CONTENT-PLAN-FAILED"
CONTENT_KNOWLEDGE_FAILED = "SHF-CONTENT-KNOWLEDGE-FAILED"
CONTENT_GENERATION_FAILED = "SHF-CONTENT-GENERATION-FAILED"
