"""Service Governance Layer 稳定错误码。"""

CONTEXT_INVALID = "SHF-SVC-GOV-CONTEXT_INVALID"
POLICY_INVALID = "SHF-SVC-GOV-POLICY_INVALID"
RETRY_EXHAUSTED = "SHF-SVC-GOV-RETRY_EXHAUSTED"
TIME_BUDGET_EXCEEDED = "SHF-SVC-GOV-TIME_BUDGET_EXCEEDED"
CIRCUIT_OPEN = "SHF-SVC-GOV-CIRCUIT_OPEN"
EXECUTION_FAILED = "SHF-SVC-GOV-EXECUTION_FAILED"

__all__ = [
    "CIRCUIT_OPEN",
    "CONTEXT_INVALID",
    "EXECUTION_FAILED",
    "POLICY_INVALID",
    "RETRY_EXHAUSTED",
    "TIME_BUDGET_EXCEEDED",
]
