"""Office Service稳定错误码。"""

OFFICE_REQUEST_INVALID = "SHF-OFFICE-REQUEST-INVALID"
OFFICE_PERMISSION_DENIED = "SHF-OFFICE-AUTH-PERMISSION_DENIED"
OFFICE_RESPONSE_INVALID = "SHF-OFFICE-RESPONSE-INVALID"
OFFICE_OPERATION_FAILED = "SHF-OFFICE-OPERATION-FAILED"
OFFICE_TOOL_NOT_FOUND = "SHF-OFFICE-TOOL-NOT_FOUND"
