"""Knowledge Service稳定错误码。"""


KNOWLEDGE_INVALID_REQUEST = "SHF-SVC-KNOWLEDGE-INVALID_REQUEST"
KNOWLEDGE_PERMISSION_DENIED = "SHF-SVC-KNOWLEDGE-PERMISSION_DENIED"
KNOWLEDGE_NOT_FOUND = "SHF-SVC-KNOWLEDGE-NOT_FOUND"
KNOWLEDGE_INVALID_RESPONSE = "SHF-SVC-KNOWLEDGE-INVALID_RESPONSE"
